#!/bin/bash
HERE=$PWD
GL=~/Downloads/graylog-4.1.3
TT=$GL/tmp
mkdir -p $TT
#sudo umount $TT
#sudo mount -o bind,noexec $TT $TT
export JAVA_OPTS="-Djava.io.tmpdir=$TT"
rm -Rf $GL/data
mkdir -p $GL/data
mvn package -DskipTests
cp target/graylog-output-syslog-4.1.3.jar $GL/plugin
export GRAYLOG_CONF=$GL/graylog.conf
#sudo sysctl -w vm.max_map_count=262144

docker rm -f elastic
docker run --name elastic -p 9200:9200 -e "discovery.type=single-node" \
    -e "cluster.routing.allocation.disk.threshold_enabled=false" \
    -d elasticsearch:7.10.1
docker rm -f mongo
docker run --name mongo -p 27017:27017 -d mongo:3.6
docker start elastic
docker start mongo
sleep 10
$GL/bin/graylogctl run

## Run two consoles additionally:
## docker run -it -p 514:514/udp -p 514:514/tcp  -p 601:601 --name syslog-ng balabit/syslog-ng:latest
## docker exec syslog-ng tail -f /var/log/messages