Vagrant.configure(2)  do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "graylog"

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'udp'
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'tcp'

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.synced_folder "..", "/graylog2-output-syslog"

  $script = <<SCRIPT
    apt-get update
	apt-get upgrade -y
	apt-get install -y openjdk-7-jre-headless rsyslog-gnutls gnutls-bin
    if [ ! -f graylog_latest.deb ]; then
		echo 'Going to download Graylog...'	
		curl -S -s -L -o /vagrant/graylog_latest.deb -O https://packages.graylog2.org/releases/graylog-omnibus/ubuntu/graylog_latest.deb
	else 
		dpkg -r /vagrant/graylog_latest.deb
	fi
    
	dpkg -i /vagrant/graylog_latest.deb
    graylog-ctl set-external-ip http://127.0.0.1:8080/api

	if [ -f /opt/graylog/conf/server.jks ]; then
		openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
			-subj "/C=ORG/ST=NET/L=Graylog/O=IT/CN=server.graylog.org" \
			-keyout server.key -out server.crt

		openssl pkcs12 -export -name servercert -in server.crt -inkey server.key -out server.p12 -passout pass:123456

		keytool -importkeystore -destkeystore server.jks -srckeystore server.p12 -srcstoretype pkcs12 -alias servercert -srcstorepass 123456 -storepass 123456	

		cp server.* /opt/graylog/conf
	fi

	cp /vagrant/rsyslog-tls.conf /etc/rsyslog.d/90-tls.conf
	service rsyslog restart

	PLUGIN=/graylog2-output-syslog/target/graylog-output-syslog-2.1.1.jar
	if [ -f $PLUGIN ]; then
		cp $PLUGIN /opt/graylog/plugin/
		graylog-ctl restart 
	fi
	
    graylog-ctl reconfigure
	
SCRIPT

  config.vm.provision "shell", inline: $script
end
